Setup hello-world backend API
sharon-odhiambo/hello-rails-back-end pull request #1
Opened 2022-12-01 06:28 UTC by sharon-odhiambo

In this PR I used a created a rails backend API to be connected with the react front-end for displaying random messages..

**Below are the highlights**

- Use Ruby on Rails to create new app
- Create a Greetings backend API endpoint
- Use Postgresql for setting up and storing the database
- Implement the correct Gitflow
- Ensure no linter errors

**Cheers and Happy Reviewing!**

2022-12-01 18:29 UTC, FrederickMih requested changes
## Hi :raising_hand: @sharon-odhiambo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


![Screenshot from 2022-10-20 09-38-51](https://user-images.githubusercontent.com/63087491/205131402-4205229e-86d6-44c7-a3ab-9ad5d3674d4a.png)


## Highlights

- Correct routes have been added :heavy_check_mark: 
- PR is descriptive :heavy_check_mark: 
- Linters are passing :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 18:29 UTC, FrederickMih commented on config/routes.rb
> +  end
- [ ] Based on the requirements of this project, the two apps should work together. Right now, the API endpoint for returning random greetings returns **null** hence could not connect properly with the client side. Kindly fix the issue


![Screenshot from 2022-12-01 19-25-38](https://user-images.githubusercontent.com/63087491/205131301-5832b2ea-a994-4167-a69f-6e618a71b19a.png)

2022-12-02 05:18 UTC, sharon-odhiambo commented
hello @FrederickMih , thank you for the review.

2022-12-02 05:24 UTC, descholar-ceo approved these changes
Hi @sharon-odhiambo 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Implemented the requested changes ✔️ 
👍🏽 The PR is following the correct  git flow ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 05:35 UTC, sharon-odhiambo commented
Hello @descholar-ceo,thank you for the review.

2022-12-02 05:35 UTC, merged